-define(LOGDIR,		"/tmp").	%% dir for log files
-define(LOGFILE_MAXB,	100000).	%% max logfile size
-define(LOGFILE_MAXF,	2).		%% max no logfiles
-define(MAX_LOGFILES,	99).
-define(INDEX_SUFFIX,		"index").
